name: Check for Prod References

on:
  push:
    paths:
      - 'Test/**'   
    branches:
      - '**'

jobs:
  scan:
    name: Scan committed files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin ${{ github.event.before }}
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'Test/')
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Scan for prod references
        run: |
          forbidden=("68b865d5-cf18-4b2b-82a4-a4eddb9c5237" "prod" "clientsecret-sp-prd" "clientid-sp-prd")
          hit=0
          
          for file in $FILES; do
            if [[ ! -f "$file" ]]; then continue; fi
            for word in "${forbidden[@]}"; do
              if grep -q -i "$word" "$file"; then
                echo "❌ Found '$word' in $file"
                hit=1
              fi
            done
          done

          if [[ "$hit" -eq 1 ]]; then
            echo "🔒 Commit blocked: Prod references found."
            exit 1
          else
            echo "✅ No Prod references found."
          fi
